accepted = [
  "Unicode-3.0",
  "ISC",
  "MIT",
  "Zlib",
  "BSL-1.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "NCSA",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "GPL-3.0",
  "AGPL-3.0"
]

targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "aarch64-unknown-linux-gnu",
  "aarch64-apple-darwin"
]

no-clearly-defined = true # https://github.com/EmbarkStudios/cargo-about/issues/269
